using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MVVMSample.Helpers
{
    // Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
    // If you change the class to 'public' in order to use it outside its assembly
    //  you should also change the fields from 'const' to 'public static readonly'
    static class IconFont
    {
        public const string Delete = "\ue872";
        public const string Zoom_out = "\ue900";
        public const string View_agenda = "\ue8e9";
        public const string Splitscreen_top = "\uf673";
        public const string Smart_toy = "\uf06c";
        public const string Toys = "\ue332";
    }
}
